### ISSUE TITLE
Publish as a hex.pm package [JIRA: CLIENTS-626]

### ISSUE THREAD

**Issue by lpil** [basho/riak-erlang-client#238]
Hello!

[hex.pm](https://hex.pm/) is a lovely little package manager for the Erlang VM.

I think it would be great if we were able to get this library through hex, rather than pulling the dependancy from github.

Documentation on doing this can be found here -> https://hex.pm/docs/publish

Thanks,
Louis

**Comment by tsloughter** [comment]
Should link to https://github.com/basho/riak-erlang-client/issues/221 as well. If the client is rebar3 compatible it can be published to hex through rebar3.

**Comment by lucafavatella** [comment]
Version 2.4.1 is on hex https://hex.pm/packages/riakc
(Hence not sure if this ticket shall be closed already.)

Would you please consider updating the package on hex to 2.5.2?

**Comment by lukebakken** [comment]
Looks like we don't own the package on `hex.pm`. I'll see what we can do.

**Comment by lucafavatella** [comment]
@lukebakken Actually the packager is very helpful and answered https://github.com/inaka/sumo_db_riak/pull/13#discussion_r102213908
It would be good if you had a chat.

**Comment by lucafavatella** [comment]
@lukebakken I understand 2.5.2 is in hex and you are a maintainer there now.

https://hex.pm/packages/riakc

**Comment by lukebakken** [comment]
@lucafavatella do you want to test this out?

https://hex.pm/packages/riakc/2.5.3-beta1

**Comment by lucafavatella** [comment]
@lukebakken Trying testing now.

**Comment by lucafavatella** [comment]
@lukebakken It looks ok. I tested that using 2.5.3-beta1 from hex you published fixes my Dialyzer warning and does not introduce regressions.
My only minor concern is that riakc errors returned by https://github.com/basho/riak-erlang-client/pull/349 (did not experience any - just speculating) are not immediate to turn off i.e. which configuration parameter to set in order to allow operation after careful analysis e.g. in development - but maybe it is designed to be difficult to turn on in the first place!

**Comment by lukebakken** [comment]
Hi everyone,

Version `2.5.3` of the Riak Erlang client and dependencies are available on [`hex.pm`](https://hex.pm/packages/riakc) now. Thank you for your patience.

**Comment by lpil** [comment]
Thank you.
